import React, { useState } from 'react';
import { GoogleGenAI } from "@google/genai";
import { X, Sparkles, AlertCircle } from 'lucide-react';

interface RecapModalProps {
  content: string;
  title: string;
  isOpen: boolean;
  onClose: () => void;
}

export const RecapModal: React.FC<RecapModalProps> = ({ content, title, isOpen, onClose }) => {
  const [recap, setRecap] = useState<string>('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  React.useEffect(() => {
    if (isOpen && !recap) {
      generateRecap();
    }
  }, [isOpen]);

  const generateRecap = async () => {
    setLoading(true);
    setError(null);
    try {
      if (!process.env.API_KEY) {
        throw new Error("API Key missing. Please configure process.env.API_KEY.");
      }

      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
      // Strip HTML tags roughly for token efficiency
      const cleanText = content.replace(/<[^>]*>?/gm, '');
      const prompt = `Summarize the following article titled "${title}" into 3 concise bullet points for a busy reader. Make it punchy and insightful.\n\nArticle Text:\n${cleanText.substring(0, 8000)}`;

      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
      });

      setRecap(response.text || "Could not generate summary.");
    } catch (err: any) {
      setError(err.message || "Failed to contact AI.");
    } finally {
      setLoading(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/80 backdrop-blur-sm" onClick={onClose}></div>
      <div className="relative bg-[#111625] border border-brand-cyan/50 rounded-2xl w-full max-w-lg p-6 shadow-[0_0_50px_rgba(6,182,212,0.2)]">
        
        <button onClick={onClose} className="absolute top-4 right-4 text-gray-400 hover:text-white">
          <X size={20} />
        </button>

        <div className="flex items-center gap-3 mb-6">
          <div className="p-2 bg-brand-cyan/10 rounded-lg">
            <Sparkles className="text-brand-cyan animate-pulse" size={24} />
          </div>
          <h3 className="text-xl font-bold text-white">AI Executive Summary</h3>
        </div>

        {loading ? (
          <div className="space-y-3 animate-pulse">
            <div className="h-4 bg-white/10 rounded w-3/4"></div>
            <div className="h-4 bg-white/10 rounded w-full"></div>
            <div className="h-4 bg-white/10 rounded w-5/6"></div>
            <p className="text-xs text-brand-cyan mt-4">Analyzing content structure...</p>
          </div>
        ) : error ? (
          <div className="text-red-400 bg-red-900/20 p-4 rounded-lg flex items-start gap-2 border border-red-500/20">
            <AlertCircle size={18} className="mt-0.5" />
            <p className="text-sm">{error}</p>
          </div>
        ) : (
          <div className="prose prose-invert prose-sm">
             <div className="whitespace-pre-line text-gray-300 leading-relaxed font-serif">
               {recap}
             </div>
             <div className="mt-6 pt-4 border-t border-white/5 flex justify-end">
               <span className="text-[10px] text-brand-muted uppercase tracking-wider">Generated by Gemini 2.5 Flash</span>
             </div>
          </div>
        )}
      </div>
    </div>
  );
};