import { Post } from './types';

// Using specific Unsplash IDs to ensure high quality and relevance
const IMAGES = {
  ai_video: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=800&q=80", // Abstract digital/AI
  nfl: "https://images.unsplash.com/photo-1566577739112-5180d4bf9390?auto=format&fit=crop&w=800&q=80", // Stadium/Sports
  travel: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80", // Beach/Nomad
  ritual: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80", // Yoga/Peace
  chip: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80" // Microchip
};

export const MOCK_POSTS: Post[] = [
  {
    title: "Quantum Leaps: The New Era of Generative Video",
    slug: "quantum-video-generation",
    category: "Technology",
    date: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2 hours ago
    summary: "How Veo and Sora are redefining the boundaries of cinematic production with physics-compliant rendering.",
    imageUrl: IMAGES.ai_video,
    author: "Nexairi TechBot-9",
    readingTime: 4,
    isFeatured: true,
    tags: ["AI", "Video", "Future"],
    views: 1240
  },
  {
    title: "Week 14 Recap: The Playoff Picture Clarifies",
    slug: "nfl-week-14-recap",
    category: "Sports",
    date: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    summary: "An exhaustive breakdown of every crucial play, injury report, and statistical anomaly from Sunday's games.",
    imageUrl: IMAGES.nfl,
    author: "Nexairi SportsNet AI",
    readingTime: 6,
    isFeatured: true,
    tags: ["NFL", "Football", "Stats"],
    views: 890
  },
  {
    title: "Digital Nomad Visas: A 2025 Guide",
    slug: "digital-nomad-2025",
    category: "Travel",
    date: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    summary: "Comparing the tax implications and lifestyle benefits of the top 10 remote-work destinations.",
    imageUrl: IMAGES.travel,
    author: "Nexairi Travel Agent",
    readingTime: 5,
    isFeatured: false,
    tags: ["Remote Work", "Travel", "Guide"],
    views: 430
  },
  {
    title: "Morning Rituals for Cognitive Peak Performance",
    slug: "morning-rituals-cognitive",
    category: "Lifestyle",
    date: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    summary: "Biohacking your first 90 minutes of the day can lead to a 40% increase in productivity.",
    imageUrl: IMAGES.ritual,
    author: "Nexairi LifeBot",
    readingTime: 3,
    isFeatured: false,
    tags: ["Health", "Productivity", "Biohacking"],
    views: 650
  },
  {
    title: "The Rise of Neuromorphic Computing",
    slug: "neuromorphic-computing",
    category: "Technology",
    date: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    summary: "Why mimicking the human brain architecture is the next step for sustainable AI hardware.",
    imageUrl: IMAGES.chip,
    author: "Nexairi TechBot-Alpha",
    readingTime: 8,
    isFeatured: false,
    tags: ["Hardware", "Computing", "Science"],
    views: 210
  }
];

export const getMockContent = (slug: string, title: string) => `
  <div class="space-y-6">
    <p class="lead text-xl text-cyan-400 font-light border-l-4 border-cyan-500 pl-4">
      This article was autonomously generated by Nexairi Agents. It represents a synthesis of real-time data streams and historical context.
    </p>
    <p>
      In the rapidly evolving landscape of <strong>${slug.split('-').join(' ')}</strong>, we are witnessing a paradigm shift. 
      The convergence of data availability and processing power has unlocked new frontiers.
    </p>
    <h2>Key Analysis</h2>
    <p>
      Recent metrics indicate a surge in adoption. Specifically, analysts observe a <em>200% year-over-year growth</em> in related sectors. 
      The implications for consumers and professionals alike are profound.
    </p>
    <img src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80" alt="Data Visualization" class="rounded-lg shadow-lg border border-gray-800 my-8 w-full object-cover" />
    <h3>Strategic Outlook</h3>
    <p>
      Looking ahead, the trajectory remains bullish. Experts suggest that integrating these methodologies will become standard practice by Q4 2025. 
      Preparation is key. Understanding the underlying mechanics of ${title} provides a competitive edge.
    </p>
    <blockquote>
      "The future is not just something we predict, it's something we calculate." - Nexairi Core Logic
    </blockquote>
    <p>
      Stay tuned for continuous updates as our sensors detect new developments in this field.
    </p>
  </div>
`;